### ISSUE TITLE
Basic Install Instructions

### ISSUE THREAD

**Issue by ghost** [aechan/sync.#3]
I came across this software while searching for alternatives to groupwatch which has a setup process which requires too much resources.

I'm just wondering whether there is a chance of you including a basic how to guide of building this software in the read me file.

**Comment by aechan** [comment]
This repository is not intended for others to use and install on their own machines, it is just intended to be used as a learning example for others interested. This software is also not open source as indicated by the lack of a license. If you would like to use the current version of sync (this is the new upcoming version), you can go to http://sync.theater
